//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public System.DateTime Date { get; set; }
        public string Mutation { get; set; }
        public decimal Amount { get; set; }
        public string Name { get; set; }
        public string CounterAccount { get; set; }
        public string Text { get; set; }
        public string Origin { get; set; }
        public string Tally { get; set; }
        public string RawText { get; set; }
    }
}
